title: Abdul Qayoom
description: Backend Developer
site_title: Abdul Qayoom's Portfolio

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: qayoom685
# blog_url: https://www.nagekar.com
email: qayoomk013@gmail.com
# keybase_username: abhn
twitter_username: akyum4
reddit_username: qayoom2

# absolute or relative
profile_picture: assets/images/profile.jpg

# Google Analytics ID
google_analytics: 